---
- name: Add repositories for php
  apt_repository: repo='ppa:ondrej/php' state=present
  retries: 25
  delay: 20
  register: result_php_repo
  until: result_php_repo is succeeded


- name: Update repositories cache and install "php" packages
  apt:
    pkg:
      - libapache2-mod-php7.3
      - php7.3
      - php7.3-xsl
      - php7.3-intl
      - php7.3-gd
      - php7.3-mbstring
      - php7.3-xml
      - php7.3-curl
      - php7.3-mysql
      - php7.3-zip
      - php7.3-soap
      - php7.3-bcmath
      - php7.3-fpm
      - php7.3-common
      - php7.3-cli
      - php7.3-bcmath
      - php7.3-curl
      - php7.3-intl
      - php7.3-soap
      - php7.3-dom
      - php-mysql
      - php7.3-simplexml
    update_cache: yes
  retries: 25
  delay: 20
  register: result_php_apt
  until: result_php_apt is succeeded