#- hosts: localhost
#  gather_facts: no
#  connection: local
#  roles:
#     - folders
#     - folder_permissions
#     - pfsense_deploy_provision
#     - template_deployment
#
#- hosts: AD
#  gather_facts: no
#  roles:
#    - windows_server_provision_AD
#
#- hosts: Rouge_Windows, CentOS, Ubuntu, WEB, DB, Gaming_Forum
#  gather_facts: no
#  strategy: free
#  tasks:
#    - name: Wait For connection up
#      wait_for_connection:
#        timeout: 30000
#
#- hosts: Rouge_Windows, CentOS, Ubuntu, WEB, DB, Gaming_Forum
#  roles:
#    - local_users_Linux
#
#- hosts: Windows_10, Windows_Core, FTP
#  gather_facts: no
#  roles:
#    - Windows_Client_Provision
#
#- hosts: WEB, DB
#  become: yes
#  roles:
#    - disable_firewall


- hosts: DB
  pre_tasks:
    - name: Install the MySQL repo.
      yum:
        name: http://repo.mysql.com/mysql57-community-release-el7-9.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat"

    - name: Override variables for MySQL (RedHat).
      set_fact:
        mysql_daemon: mysqld
        mysql_packages: ['mysql-community-server']
        mysql_log_error: ""
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
      when: ansible_os_family == "RedHat"
  become: true
  roles:
    - ansible-role-mysql-master


- hosts: WEB
  become: true
  roles:
#    - geerlingguy.composer
    - install_php
    - ansible-role-apache-master
    - ansible-role-composer-master
    - install_magento

- hosts: DB
  become: true
  roles:
    - ansible-docker-master


- hosts: Gaming_Forum
  become: true
  roles:
    - ansible-discourse-role