- hosts: localhost
  gather_facts: no
  connection: local
  roles:
#     - folders
#     - folder_permissions
#     - pfsense_deploy_provision
     - template_deployment

#- hosts: AD
#  gather_facts: no
#  roles:
#    - windows_server_provision_AD
#
#- hosts: Linux-A, Linux-B, Linux-C, WEB, DB, GIT
#  gather_facts: no
#  tasks:
#    - name: Wait For connection up
#      wait_for_connection:
#        timeout: 30000
#        sleep: 5
#
#- hosts: Linux-A, Linux-B, Linux-C, WEB, DB, GIT
#  roles:
#    - local_users_Linux
#
#- hosts: Windows-A, Windows-B, FTP
#  gather_facts: no
#  roles:
#    - Windows_Client_Provision
#
#- hosts: GIT, WEB, DB
#  become: yes
#  roles:
#    - disable_firewall
#
#- hosts: GIT
#  gather_facts: no
#  become: yes
#  roles:
#    - gitlab
#
#- hosts: DB
#  gather_facts: no
#  become: true
#  pre_tasks:
#    - name: install python2
#      raw: apt-get -y install python
#  roles:
#    - ansible-role-mariadb
#
#- hosts: WEB
#  become: true
#  roles:
#    - mediawiki
#
#- hosts: WEB, DB
#  become: true
#  roles:
#    - ansible-docker-master