- debug:
    msg: {{ mysql_log_error }}

- name: Acquire temporary root pass
  shell: >
      awk '$0 ~ "temporary password" {print $11}' {{ mysql_log_error }} | tail -1
  register: mysql_root_temp_password
  when: (mysql_install_packages | bool) and ('5.7.' in mysql_cli_version.stdout)

- debug:
    var: mysql_root_temp_password

- name: Copy .my.cnf file with temporary root password credentials
  template:
      src: "root-temporary-my.cnf.j2"
      dest: "{{ mysql_root_home }}/.my.cnf"
      owner: root
      group: root
      mode: 0600
  when: mysql_root_temp_password is not skipped

- name: Test temporary root password expired
  shell: "mysql -NBe 'SELECT NOW();'"
  register: mysql_temp_password_test_result
  when: mysql_root_temp_password is not skipped
  ignore_errors: yes

- debug: var=mysql_temp_password_test_result

- name: Update MySQL root password for localhost root account (5.7.x).
  shell: >
      mysql -NBe 'ALTER USER "{{ mysql_root_username }}"@"localhost" IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";'
      --connect-expired-password
  when: mysql_temp_password_test_result is not skipped and 'connect-expired-password' in mysql_temp_password_test_result.stdout

- name: Overwrite .my.cnf file with root password credentials.
  template:
    src: "root-my.cnf.j2"
    dest: "{{ mysql_root_home }}/.my.cnf"
    owner: root
    group: root
    mode: 0600
  when: mysql_root_temp_password is not skipped