accounts:

  - username: Admin
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Pumpkin
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Annabelle
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Flowey
    password: Changeme2020!
    groups:
      - Domain Admins
 
  - username: Freddy
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Jason
    password: Changeme2020!
    groups:
      - Domain Admins   

  - username: Michael
    password: Changeme2020!
    groups:
      - Domain Admins
    
  - username: Krampus
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Cheif
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Jigsaw
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Grudge
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Chuckie
    password: Changeme2020!
    groups:
      - Domain Admins
  
  - username: Clown
    password: Changeme2020!
    groups:
      - Domain Admins  
  
  - username: Goose
    password: Changeme2020!
    groups:
      - Domain Admins 

  - username: Ghostface
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Dracula
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Slenderman
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Torrance
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Leatherface
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Edward
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Frankenstein
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Phantom
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: VanHelsing
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Never
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Gonna
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Give
    password: Changeme2020!
    groups:
      - Domain Admins

  - username: Youu
    password: Changeme2020!
    groups:
      - Domain Admins


  - username: Uppp
    password: Changeme2020!
    groups:
      - Domain Admins
